steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-m', '30g', '-t', 'gcr.io/scdney-2024/workshop:alpha', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/scdney-2024/workshop:alpha']
options:
  machineType: 'N1_HIGHCPU_4'
  logging: CLOUD_LOGGING_ONLY
timeout: 9600s
