steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-m', '30g', '-t', 'gcr.io/scdney-2024/workshop:alpha', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/scdney-2024/workshop:alpha']
options:
  machineType: 'N2-STANDARD-8'
timeout: 9600s
